### PR TITLE
[WIP] Allow nested symbolic combinations.

### PR DESCRIPTION
**Pull request by beauby**
# Purpose
Allow nested combination directives for configured associations.

# Before this PR
`#combine` accepts either a hash with primary keys `:one` and `:many` with values describing target relations, or an array of symbols representing configured associations.

# After this PR
`#combine` also accepts hashes/arrays of symbols. The formal grammar is as follows:
`S → Hash{Symbol => S} | Array<Symbol, Hash{Symbol => S}>`

Example: 
```ruby
{ 
  posts: [ 
    :tags, 
    comments: [:author], 
    author: [:comments, :author]
  ], 
  comments: [:author] 
}
```

# Status
Tests are currently failing because the `labels` of `posts` in the test db are linked via a join table (`posts_labels`), which makes the resulting `labels` have a `post_id` attribute which the `ROM::Struct[Label]` does not accept via constructor. I'm currently not familiar enough with ROM to know exactly what's going on. Any advice? /cc @solnic

### CODE REVIEW

**Comment by solnic** [comment]
Before expanding this API we really need to refactor it. After adding support for associations the code got very complex and it's now hard to work with it.

> Tests are currently failing because the labels of posts in the test db are linked via a join table (posts_labels), which makes the resulting labels have a post_id attribute which the ROM::Struct[Label] does not accept via constructor

This is one of the problems we have now, there's an inconsistency in behavior between manual combines vs combines inferred from associations. Mappers used by combines are able to drop join keys, whereas with associations this does not happen. That's one of the reasons why I want to refactor and clean up the code, so that this inconsistency can be fixed.

**Comment by beauby** [comment]
Sounds sensible – any way I can help with that?

**Comment by solnic** [comment]
@beauby sure, you can try refactoring combine code to make it simpler to extend :)

**Comment by beauby** [comment]
@solnic After investigating this a bit, it seems the following does not work either:
```ruby
def users_with_posts_and_labels
  users.combine(many: { posts: posts.combine(many: labels) })
end
```

**Comment by solnic** [comment]
@beauby you need to use `combine_children` or `combine_parent` as they figure out how to combine whereas plain `combine` needs more info re pk/fk

**Comment by solnic** [comment]
@beauby I tweaked the spec so that it's passing and pushed rebased/squashed commits to master. I'm gonna work on this more though as I want to make it work consistently wrt relation attributes (specifically so that using associations results in the same tuples as when you use ad-hoc combines)

**Pull request closed without merging**
