### PR TITLE
Use named argument to avoid mutating input parameters

### PR DESCRIPTION
**Pull request by cflipse**

### CODE REVIEW

**Comment by flash-gordon** [comment]
@cflipse unfortunately that wouldn't work. The problem is `commands.fetch_or_store(all_args.hash)` where `all_args` variable is required to contain all input arguments otherwise we can encounter false-positive cache hit which will lead to a weird error.

**Comment by cflipse** [comment]
Makes some sense ... Also easy enough to add the mapper into that arg cache.

As Travis seems to think that all is right with the world, would you mind putting together a test to ensure the cache is behaving as you expect?  File in another PR, and I'll merge it in

**Comment by flash-gordon** [comment]
Yeah, it's a little bit tricky so we need to add some protection. I'll add some specs, thanks.
What do you think about that version of `#command`:

``` ruby
    def command(*args, **opts, &block)
      all_args = args + opts.to_a.flatten

      if all_args.size > 1
        commands.fetch_or_store(all_args.hash) do
          if args.size > 0
            type, name = args
          else
            type, name = opts.find { |k, _| CommandCompiler.support?(k) }
          end

          relation = name.is_a?(Symbol) ? relations[name] : name

          ast = relation.to_ast
          adapter = relations[relation.name].adapter

          if opts[:mapper]
            mapper = container.mappers[relation.name][opts[:mapper]]
          else
            mapper = mappers[ast]
          end

          CommandCompiler[container, type, adapter, ast] >> mapper
        end
      else
        container.command(*args, &block)
      end
    end
```

/cc @solnic

**Comment by cflipse** [comment]
It's better than `delete` ...

Maybe the "nice" solution is to split  the cache guard and the acutal command generation into different methods?  So, you check the cache, and if it falls through, pass the args onto a method that actually calls out what it's expecting?

**Comment by solnic** [comment]
yeah this method is way too complex now

**Comment by flash-gordon** [comment]
OK, should be fine now: https://github.com/rom-rb/rom-repository/commit/9de4100eb8dc0c8fb8de6d6de5744267ae48158c 
I also added a spec for caching here https://github.com/rom-rb/rom-repository/commit/b93ffb115a2ed3cde7605349779389779b18c672

**Comment by flash-gordon** [comment]
@cflipse is it OK now? :)

**Comment by cflipse** [comment]
Yep, looks better.

**Pull request closed without merging**
