### PR TITLE
Remove rom-support dependency

### PR DESCRIPTION
**Pull request by flash-gordon**
Now use dry-initializer + dry-core instead :tada:

### CODE REVIEW

**Comment by flash-gordon** [comment]
@solnic [this](https://github.com/rom-rb/rom-sql/commit/a893184e945c1281f41bb855772cbea285f2a2bc) makes specs fail on MRI 2.2 because `[ROM::SQL::Function.new(Object.new)].flatten` hangs on indefinitely (obviously due to `def to_ary` presence). `.flatten` with no args is called [in rom-mapper](https://github.com/rom-rb/rom-mapper/blob/21dc660419afa29bc72e3b83567bf84d13c83d1c/lib/rom/header.rb#L187). I tried to remove `flatten` and rom-mapper's tests still pass :-/ . Replacing `flatten` with `flatten(1)` also works. WDYT?

**Comment by solnic** [comment]
@flash-gordon thanks for help, I wrapped this up and merged

**Comment by flash-gordon** [comment]
@solnic so we need a disclaimer at rom-support's page that it has been decommissioned?

**Comment by solnic** [comment]
Yes we do

Cheers
Piotr

**Pull request merged**
